# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2011(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bucket_id=None, message=None):  # noqa: E501
        """InlineResponse2011 - a model defined in OpenAPI

        :param bucket_id: The bucket_id of this InlineResponse2011.  # noqa: E501
        :type bucket_id: str
        :param message: The message of this InlineResponse2011.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'bucket_id': 'str',
            'message': 'str'
        }

        self.attribute_map = {
            'bucket_id': 'bucket_id',
            'message': 'message'
        }

        self._bucket_id = bucket_id
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2011':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_1 of this InlineResponse2011.  # noqa: E501
        :rtype: InlineResponse2011
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bucket_id(self):
        """Gets the bucket_id of this InlineResponse2011.


        :return: The bucket_id of this InlineResponse2011.
        :rtype: str
        """
        return self._bucket_id

    @bucket_id.setter
    def bucket_id(self, bucket_id):
        """Sets the bucket_id of this InlineResponse2011.


        :param bucket_id: The bucket_id of this InlineResponse2011.
        :type bucket_id: str
        """

        self._bucket_id = bucket_id

    @property
    def message(self):
        """Gets the message of this InlineResponse2011.


        :return: The message of this InlineResponse2011.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse2011.


        :param message: The message of this InlineResponse2011.
        :type message: str
        """

        self._message = message
