# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject3(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, model_id=None, features=None, target=None):  # noqa: E501
        """InlineObject3 - a model defined in OpenAPI

        :param model_id: The model_id of this InlineObject3.  # noqa: E501
        :type model_id: str
        :param features: The features of this InlineObject3.  # noqa: E501
        :type features: Features
        :param target: The target of this InlineObject3.  # noqa: E501
        :type target: Curve
        """
        self.openapi_types = {
            'model_id': 'str',
            'features': 'Features',
            'target': 'Curve'
        }

        self.attribute_map = {
            'model_id': 'model_id',
            'features': 'features',
            'target': 'target'
        }

        self._model_id = model_id
        self._features = features
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject3':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_3 of this InlineObject3.  # noqa: E501
        :rtype: InlineObject3
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_id(self):
        """Gets the model_id of this InlineObject3.


        :return: The model_id of this InlineObject3.
        :rtype: str
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """Sets the model_id of this InlineObject3.


        :param model_id: The model_id of this InlineObject3.
        :type model_id: str
        """
        if model_id is None:
            raise ValueError("Invalid value for `model_id`, must not be `None`")  # noqa: E501

        self._model_id = model_id

    @property
    def features(self):
        """Gets the features of this InlineObject3.


        :return: The features of this InlineObject3.
        :rtype: Features
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this InlineObject3.


        :param features: The features of this InlineObject3.
        :type features: Features
        """
        if features is None:
            raise ValueError("Invalid value for `features`, must not be `None`")  # noqa: E501

        self._features = features

    @property
    def target(self):
        """Gets the target of this InlineObject3.


        :return: The target of this InlineObject3.
        :rtype: Curve
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this InlineObject3.


        :param target: The target of this InlineObject3.
        :type target: Curve
        """
        if target is None:
            raise ValueError("Invalid value for `target`, must not be `None`")  # noqa: E501

        self._target = target
