# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject1(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dims=None):  # noqa: E501
        """InlineObject1 - a model defined in OpenAPI

        :param dims: The dims of this InlineObject1.  # noqa: E501
        :type dims: int
        """
        self.openapi_types = {
            'dims': 'int'
        }

        self.attribute_map = {
            'dims': 'dims'
        }

        self._dims = dims

    @classmethod
    def from_dict(cls, dikt) -> 'InlineObject1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_object_1 of this InlineObject1.  # noqa: E501
        :rtype: InlineObject1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dims(self):
        """Gets the dims of this InlineObject1.


        :return: The dims of this InlineObject1.
        :rtype: int
        """
        return self._dims

    @dims.setter
    def dims(self, dims):
        """Sets the dims of this InlineObject1.


        :param dims: The dims of this InlineObject1.
        :type dims: int
        """
        if dims is None:
            raise ValueError("Invalid value for `dims`, must not be `None`")  # noqa: E501

        self._dims = dims
